### ISSUE TITLE
Customizing the shortcut

### ISSUE THREAD

**Issue by jianzhizhipeng** [jieYM/key2mouse#1]
Hi, I am very glad to find your genius developed lite soft, but two requirement. It's quite a helpful tool for protecting us from some potential diseases caused by frequently using of mouse. 
First, can you open the access to customize the shortcut according to our personal habit?
Second, can you find a solution to realize the simultaneously typing and moving. That's efficiency up! 

Your design is quite perfect enough, just for giving personal suggestion.

**Comment by jieYM** [comment]
> Hi, I am very glad to find your genius developed lite soft, but two requirement. It's quite a helpful tool for protecting us from some potential diseases caused by frequently using of mouse.
> First, can you open the access to customize the shortcut according to our personal habit?
> Second, can you find a solution to realize the simultaneously typing and moving. That's efficiency up!
> 
> Your design is quite perfect enough, just for giving personal suggestion.

I am happy to hear that.
And yes, the next version can config shortcut in config file. Include config the moving by press Space/CapsLock + moving key,  and release Space/CapsLock return normal keyboard status. 

Please look forward to next version.

**Comment by jianzhizhipeng** [comment]
Good news, let's wait for the next release! 


Cheers


| |
渐之
|
|
linzhipengzhuce@163.com
|
签名由网易邮箱大师定制
On 10/21/2020 14:16，Michael_Jie<notifications@github.com> wrote：

Hi, I am very glad to find your genius developed lite soft, but two requirement. It's quite a helpful tool for protecting us from some potential diseases caused by frequently using of mouse.
First, can you open the access to customize the shortcut according to our personal habit?
Second, can you find a solution to realize the simultaneously typing and moving. That's efficiency up!

Your design is quite perfect enough, just for giving personal suggestion.

I am happy to hear that.
And yes, the next version can config shortcut in config file. Include config the moving by press Space/CapsLock + moving key, and release Space/CapsLock return normal keyboard status.

Please look forward to next version.

**Comment by ToonoW** [comment]
啊 习惯了vim的键位，能不能自己自定义，或者就用vim的键位设置控制上下左右？

**Comment by jieYM** [comment]
> 啊 习惯了vim的键位，能不能自己自定义，或者就用vim的键位设置控制上下左右？

下一个版本可以自定义， 以及可以配置通过按住空格键或大写键+其他键的方式移动， 释放即恢复键盘原始输入模式。

近期就会更新， 敬请期待。

**Comment by jieYM** [comment]
v2.0 had release,  these feature working in v2.0
