### ISSUE TITLE
远距离移动时，更快更准移动的建议

### ISSUE THREAD

**Issue by photkey** [jieYM/key2mouse#4]
首先不得不说，这个项目真的非常棒，连续找了好几天，终于找到一款就像私人订制一样称心如意的！
也可能是因为刚开始使用还不够习惯的原因，如论如何，我认为 下面的建议都会加快鼠标**远距离移动**时的效率。

首先是需要在现在基础上 再增加一个远距离专用的快捷键，当按下这个键的时候，按照下面图片那样 把屏幕切割成 26*26个区域，每个区域分配两个字母的组合，当按下这两个字母的时候，鼠标移动到对应区域的中心点位置；然后自动切换到` mouse mode`，后面就跟现有的操作完全一致了。键盘模拟鼠标移动时 无论多远的距离，只需要在屏幕的1/676的范围内移动即可 (26X26=676)

![key2mouse](https://user-images.githubusercontent.com/60434581/145061639-8fb9104f-18f3-43fc-a38d-9aed5ce90096.png)
PS：前25行我是直接复制的相同内容，不能真去手敲676组字母……意思应该是可以看明白的哈。

另外，这676个中心点的位置，应该不需要每次启动时都去计算一遍。首次启动时，计算一次，然后把这些位置跟对应的字母缓存下来，应该可以加快启动速度。

如果大佬有兴趣实现的话，有现成的脚本 [ScreenGrid.zip](https://github.com/jieYM/key2mouse/files/7669714/ScreenGrid.zip) 可以参考（可能），是在AHK群里看的，不过他只把当前激活的窗口分了26份，使用起来太磨叽，可能还不如直接用你现有的移动方式高效。

**Comment by photkey** [comment]
这个图看起来可能第一感觉比较乱，满屏的字母；实际使用时，当按下快捷键的同时，眼睛只需要盯着 鼠标要去的那个位置的两个字母，其它位置根本不需要去看。

**Comment by photkey** [comment]
另外我算错了，鼠标只需要在屏幕的1/(26*26)/2=1/1352范围内移动。因为定位的是中心点，即使没有一次定位准，鼠标也只需要在这个区域的一半面积内移动。

**Comment by brother-darion** [comment]
> 

好的，有空我研究下，一开始我也是考虑这种分割的方式，但是由于太不优雅，而且还不灵活就没用。但是整合起来倒是没想到，有空可以研究下。

**Comment by brother-darion** [comment]
> 首先不得不说，这个项目真的非常棒，连续找了好几天，终于找到一款就像私人订制一样称心如意的！ 也可能是因为刚开始使用还不够习惯的原因，如论如何，我认为 下面的建议都会加快鼠标**远距离移动**时的效率。
> 
> 首先是需要在现在基础上 再增加一个远距离专用的快捷键，当按下这个键的时候，按照下面图片那样 把屏幕切割成 26*26个区域，每个区域分配两个字母的组合，当按下这两个字母的时候，鼠标移动到对应区域的中心点位置；然后自动切换到` mouse mode`，后面就跟现有的操作完全一致了。键盘模拟鼠标移动时 无论多远的距离，只需要在屏幕的1/676的范围内移动即可 (26X26=676)
> 
> ![key2mouse](https://user-images.githubusercontent.com/60434581/145061639-8fb9104f-18f3-43fc-a38d-9aed5ce90096.png) PS：前25行我是直接复制的相同内容，不能真去手敲676组字母……意思应该是可以看明白的哈。
> 
> 另外，这676个中心点的位置，应该不需要每次启动时都去计算一遍。首次启动时，计算一次，然后把这些位置跟对应的字母缓存下来，应该可以加快启动速度。
> 
> 如果大佬有兴趣实现的话，有现成的脚本 [ScreenGrid.zip](https://github.com/jieYM/key2mouse/files/7669714/ScreenGrid.zip) 可以参考（可能），是在AHK群里看的，不过他只把当前激活的窗口分了26份，使用起来太磨叽，可能还不如直接用你现有的移动方式高效。

好的，有空我研究下，一开始我也是考虑这种分割的方式，但是由于太不优雅，而且还不灵活就没用。但是整合起来倒是没想到，有空可以研究下。

**Comment by photkey** [comment]
谢谢 你的回复。我又找了两个参考项目，但是由于我不懂AHK语法，我甚至不知道它的启动热键是什么，不过从readme来看，应该是需要的东西。
https://github.com/GavinPen/AhkCoordGrid
https://github.com/itmitica/AhkCoordGrid（复刻自上一个，应该有改进）

**Comment by brother-darion** [comment]
> 谢谢 你的回复。我又找了两个参考项目，但是由于我不懂AHK语法，我甚至不知道它的启动热键是什么，不过从readme来看，应该是需要的东西。 https://github.com/GavinPen/AhkCoordGrid [https://github.com/itmitica/AhkCoordGrid（复刻自上一个，应该有改进）](https://github.com/itmitica/AhkCoordGrid%EF%BC%88%E5%A4%8D%E5%88%BB%E8%87%AA%E4%B8%8A%E4%B8%80%E4%B8%AA%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%9C%89%E6%94%B9%E8%BF%9B%EF%BC%89)

README说的是数字键盘的回车，但代码里写的应该是Ctrl + 分号(;)

**Comment by photkey** [comment]
奥，我的键盘还没有数字区，那可能是跟 https://github.com/itmitica/slimwin 这个项目的mhits.ahk差不多，我还是认为更好的移动方式还是把两种整合：远距离2键定位+小范围内移动。
可惜我不会ahk，只能期待你有时间的话 研究一下，已经订阅了这个项目的所有通知哈。

**Comment by brother-darion** [comment]
> 奥，我的键盘还没有数字区，那可能是跟 https://github.com/itmitica/slimwin 这个项目的mhits.ahk差不多，我还是认为更好的移动方式还是把两种整合：远距离2键定位+小范围内移动。 可惜我不会ahk，只能期待你有时间的话 研究一下，已经订阅了这个项目的所有通知哈。

我也觉得是个不错的想法，有空我研究下

**Comment by photkey** [comment]
想了一下细节，现在说的远距离移动 启动的顺序是：26*26网格（简称 `key mode`）→`mouse mode`；实际使用时，有可能会误触 按错键，所以可能还需要增加一个设置，在`mouse mode`下，按一个键 再次进入`key mode`
即使不是误触，这个键的设置好像也是有必要的，在一段时间内持续使用`mouse mode`时，可能需要多次进入`key mode`，按一个键 肯定是比按组合键 更舒服一些。

**Comment by brother-darion** [comment]
> 想了一下细节，现在说的远距离移动 启动的顺序是：26*26网格（简称 `key mode`）→`mouse mode`；实际使用时，有可能会误触 按错键，所以可能还需要增加一个设置，在`mouse mode`下，按一个键 再次进入`key mode` 即使不是误触，这个键的设置好像也是有必要的，在一段时间内持续使用`mouse mode`时，可能需要多次进入`key mode`，按一个键 肯定是比按组合键 更舒服一些。

对的，这个是要考虑的，多次的需求肯定是存在的。

**Comment by blacksheepaul** [comment]
感觉这个功能有点像 vim 的 easymotion 插件，期待

**Comment by photkey** [comment]
@noyidoit 对的，我还有另外一个受easymotion启发想到的alt-tab替代品，感觉应该是最高效的alt-tab功能，但没能力开发：https://github.com/photkey/alt-tab （只是想法），@brother-darion 老大可以顺便看下有没有兴趣实现。
可供参考的AHK项目：https://github.com/monoblaine/alttab-replacer （提了issue 没反馈）

**Comment by brother-darion** [comment]
> @noyidoit 对的，我还有另外一个受easymotion启发想到的alt-tab替代品，感觉应该是最高效的alt-tab功能，但没能力开发：https://github.com/photkey/alt-tab （只是想法），@brother-darion 老大可以顺便看下有没有兴趣实现。 可供参考的AHK项目：https://github.com/monoblaine/alttab-replacer （提了issue 没反馈）

这种方式按键可能重复的概率太大，一旦重复就不高效了，可能我之前写的一些小脚本还高效一点，可以去看看我之前分享的视频https://www.bilibili.com/video/BV1q7411f7jy?share_source=copy_web ，视频最后有介绍这几个小脚本，如果有兴趣我再共享出来

**Comment by photkey** [comment]
不会的，可能您没有仔细看，常用软件 是手动分配固定、不重复的字母，不常用软件是随机分配 跟 菜单前面部分不重复的字母。这些字母跟软件的首字母并没有关系。我先看下您的分享视频，需要这些提高工作效率的脚本，我也是准备做个UP主 分享这类的工具啥的。

**Comment by brother-darion** [comment]
> 不会的，可能您没有仔细看，常用软件 是手动分配固定、不重复的字母，不常用软件是随机分配 跟 菜单前面部分不重复的字母。这些字母跟软件的首字母并没有关系。我先看下您的分享视频，需要这里提供工作效率脚本，我也是准备做个UP主 分享这类的工具啥的。

行，有空我研究下

**Comment by photkey** [comment]
视频看完了，前面推荐的软件或者插件基本都是一直是在用的，握个抓……
Listary 推荐可以试试 Flow Launcher，应该是原来Wox作者重新开发的项目（可能），开源免费 ，提issue 回复又快又热情，像你一样，哈哈。开发插件方便，我这半吊子水平都可以写自己用的python插件，您好像正是python开发者吧。

**Comment by brother-darion** [comment]
好，有空看看。对，我本职是Python开发

**Comment by jieYM** [comment]
3.0 已经新增了该功能，从Releases 下载3.0的zip包，运行exe文件，源码还没上传到github，不要从源码的方式运行。

另外：鼠标模式下默认按b可以进入定位模式（可通过配置该成其他按键），从定位模式进入鼠标模式，默认切换成了level1的速度，用于精准定位，如果有改动leve1的速度，建议保持默认或者不要改太大。

**Comment by photkey** [comment]
Ctrl+L进入 `定位模式`时，感觉比从`鼠标模式`按b再次进入`定位模式`要慢一点点，是错觉吗？

**Comment by jieYM** [comment]
> Ctrl+L进入 `定位模式`时，感觉比从`鼠标模式`按b再次进入`定位模式`要慢一点点，是错觉吗？

是程序启动后第一次进入`定位模式`吗，如果是程序刚启动会有可能，可能还没加载完。如果是程序启动了很久，或者已经进入过`定位模式`正常应该不会。

**Comment by photkey** [comment]
昨天比较忙，就试了几次，感觉加载慢；刚才又试了一会儿，速度可以，够用的。整体来说非常好用！
另外不知道字母是不是可以实现描边，比方说黄字如果可以加个黑边，应该不论什么背景都可以显示的更清晰一点；
字体、颜色这些也想自定义，如果有源码的话 应该直接从源码改就可以了吧。

**Comment by jieYM** [comment]
我也很不满意字体属性，但UI这一块确实比较难搞，我的git没配好，还上传不了代码，有空我弄一下上传上来，你可以试试从源码修改

**Comment by photkey** [comment]
好的，另外还有一个问题，就是在启用 定位模式 输入字母时，能不能禁用输入法，像鼠标模式那样。这个倒不影响使用，就是看着有点难受。

**Comment by jieYM** [comment]
好的，看后面如果有时间我就处理一下。

**Comment by photkey** [comment]
又发现一个增加快速定位的好方法，来自：https://github.com/snomiao/capslockx

 **指针移动时会自动黏附各种按钮、超链接。**


`定位模式`按下字母后，如果能自动黏付最近的按钮、超链接，又可以进一步提高定位速度和精度了。（参考的这个脚本，我是从字面意思理解的，并没有测试）

**Comment by brother-darion** [comment]
> 

看看是不是只支持网页内的，还是所有程序都支持，如果只是网页内的，那就用一个叫Surfingkey的插件，在网页内这个插件基本可以完全释放鼠标，而且定位以及各种操作都极其快速。

**Comment by photkey** [comment]
问了一下作者是全局生效的，但是对这个项目没有帮助，他说原理是根据鼠标指针的变化。

Srufingkey插件我也一直在用的，确实神器，好用。

**Comment by brother-darion** [comment]
其实这些方案我都考虑过，但是还是觉得这种方式不怎么优雅，觉得有点笨，就没有去弄。不过这些只是个人喜好，不是说这位作者的方案不好，只是不符合我个人的喜好。

**Comment by photkey** [comment]
恩，其实现在已经足够好用了，我一般是点击不是当前激活的窗口的时候，才需要用到。如果是在当前激活的窗口内点击，有更好用的（KeyMouse），跟浏览器的Surfingkey一样。比方下图这样。
![image](https://user-images.githubusercontent.com/60434581/148402689-b1db0a27-778e-468b-916d-b191ffd75ffe.png)

**Comment by brother-darion** [comment]
哇，这个很好呀，我之前一直在找这样的软件都没找到，厉害！

**Comment by photkey** [comment]
https://github.com/photkey/alt-tab （就叫他Altab吧）如果是可以开发出来这个，在鼠标点击按钮这个使用场景下，就可以实现，夸应用的3键精准点击，还要加一个启动快捷键（配合KeyMouse专用的快捷键）。
比方需要切换应用点击的时候，就只有按下 Altab的快捷键，这时候只需要一个 字母按键，就可以切换应用，当切换应用后 自动按下 KeyMouse的快捷键，只需要的再按 两个字母，就实现点击了。
总共按下的键：一个快捷键，三个字母键。

**Comment by brother-darion** [comment]
这样确实挺高效的，要是以前我就去弄了，现在一方面没啥时间，另一方面转到Mac阵营后，没太大动力动Windows下的东西了。

**Comment by photkey** [comment]
好像转Mac几乎是程序员的必经之路……不过现在Windows感觉已经是越来越好用了，尤其是有AHK的加持，很多效率神器。再给你推荐个komorebi，类似Linux下的i3wm或者dwm，平铺窗口管理器。
Windows期待你的回归。

**Comment by brother-darion** [comment]
多谢推荐。回不去了，Mac太好用了，我在Windows也是专攻效率神器多年，结果转Mac一年就被全面秒杀了，性能，美观，简洁，效率上全面秒杀，强大的命令行更是提供了无限可能，Windows多年的成果在Mac下不堪一击。
